### ISSUE TITLE
Bot is repetitively posting one flight

### ISSUE THREAD

**Issue by tris** [tomasbedrich/xcontest-rss-monitor#182]
The bot has been posting this flight over and over today, both in DM and to our group:

https://www.xcontest.org/world/en/flights/detail:aerocooper/11.10.2023/19:03

It's not happening on my local instance, which makes me wonder if perhaps the machine ran out of disk space (i.e. can't update its database)?

**Comment by tomasbedrich** [comment]
It should be fixed by 44f8156d545841761677de198346046073462f7f.

This happens due to https://github.com/tomasbedrich/xcontest-rss-monitor/blob/master/telegram_bot.py#L293, i.e. state is saved only once after the whole loop. Should there occur an unhandled exception within the loop, the previous state is retained. This means that if there is an unhandled exception during posting flight num. 6, flights num. 1-5 are posted again and again...

FWIW: There is a Sentry monitoring, so I am usually aware of the situation and will fix it eventually.
